---
- name: Update web hosts
  hosts: webservers
  serial: 1
  remote_user: robb
  become: yes
  become_user: root

  tasks:
    - name: Ensure socat is installed on HAProxy
      yum:
        name: socat
        state: latest
      delegate_to: rh8-proxy

    - name: Disable the server in haproxy
      shell: echo "disable server habackend/{{ inventory_hostname }}" | /usr/bin/socat stdio /var/lib/haproxy/stats
      delegate_to: rh8-proxy

    - name: Update packages
      yum:
        name: "*"
        state: latest

    - name: Ensure dnf-utils is installed
      yum:
        name: dnf-utils
        state: latest
  
    - name: Check if host needs a reboot
      command: /usr/bin/needs-restarting -r
      register: reboot_check
      ignore_errors: true
      changed_when: false

    - name: Reboot host if required
      reboot:
      when: reboot_check.rc == 1

    - name: Ensure the web container is running.
      docker_container:
        name: webapp-demo
        image: webapp-demo
        state: started
        ports:
          - "8080:80"
        volumes:
          - /home/robb/webpage:/var/www/html

    - name: Enable the server in haproxy
      shell: echo "enable server habackend/{{ inventory_hostname }}" | socat stdio /var/lib/haproxy/stats
      delegate_to: rh8-proxy

...
